# Header
menu:
  Home: /

# banner
banner: https://qiniu.sukoshi.xyz/src/images/68686407_p0.jpg

#
notice: Refactored part of the gentoo-docs theme, see https://github.com/ddthien-coder/gentoo-docs for details

#
author:
  name: ddthien
  avatar: https://s.gravatar.com/avatar/2d6b803eea37de0257620d5fabee7e64?s=200&r=g&d=retro
  description: Persistence

toc:
  max_depth: 3 #
  min_depth: 2 #

comments:
  enable: false
  use: 'valine' # valine || disqus
  # valine
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  valine:
    appId:
    appKey:
    avatar: mm
    placeholder: Gentoo～
    notify: true
    visitor: true
    pageSize: 10
  # disqus
  # docs: https://disqus.com/
  disqus:
    website:
    error: If you can’t see the comment, then you really can’t see the comment w(゜Д゜)w

# dplayer
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

#
beian:

# google
google_analytics:
# gauges
gauges_analytics:
# ico
favicon: /favicon.ico


# Social Icon
social_icon:
  enable: true
  icons:
    github  : https://github.com/ddthien-coder/
    twitter : https://github.com/ddthien-coder/gentoo-docs